DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers(
    id INT AUTO_INCREMENT PRIMARY KEY,            
    BURGER_NAME VARCHAR(30) NOT NULL,  
    DEVOURED BOOLEAN NOT NULL DEFAULT false    
);
